name = "miniFAVOR"
version = "1.0.0"
license = "BSD"
author = ["Patrick Raynaud", "Brad Richardson", "Damian Rouson"]
maintainer = "damian@sourceryinstitute.org"
copyright = "2021 Sourcery, Inc."

[dependencies]
sourcery = {git = "https://github.com/sourceryinstitute/sourcery", tag = "21.02.24"}

[dev-dependencies]
vegetables = {git = "https://gitlab.com/everythingfunctional/vegetables", tag = "v6.0.1"}

[[test]]
name="unit"
source-dir="tests/unit"
main="main.f90"

[[test]]
name="integration"
source-dir="tests/integration"
main="main.f90"
