! Generated by make_vegetable_driver. DO NOT EDIT
program main
    implicit none

    call run()
contains
    subroutine run()
        use whole_shebang_tests, only: &
                whole_shebang_tests_test_output_data => test_output_data
        use vegetables, only: test_item_t, test_that, run_tests

        type(test_item_t) :: tests
        type(test_item_t) :: individual_tests(1)

        individual_tests(1) = whole_shebang_tests_test_output_data()
        tests = test_that(individual_tests)

        call run_tests(tests)
    end subroutine
end program
