reference_wrapper – miniFAVOR
reference_wrapper Function
22 statements
Source File
public function reference_wrapper(input_data) result(output_data)
Uses
reference_minifavor_m
reference_inputs_h
reference_outputs_h
Arguments
Type Intent Optional Attributes Name
type(input_data_t), intent(in) :: input_data
Return Value type(output_data_t)
Calls
Called by
Contents
None
Call graph
reference_wrapper calls reference_minifavor
reference_minifavor calls ki_t, cf, rtndt, cpi_t
check_whole_shebang calls reference_wrapper