reference_minifavor – miniFAVOR
reference_minifavor Subroutine
35 statements
Source File
public subroutine reference_minifavor()
Uses
reference_inputs_h
reference_outputs_h
reference_calc_rtndt
reference_calc_k
reference_calc_cpi
Arguments
None
Calls
Called by
Contents
None
Call graph
reference_minifavor calls ki_t, cf, rtndt, cpi_t
reference_wrapper calls reference_minifavor
check_whole_shebang calls reference_wrapper