whole_shebang – miniFAVOR
whole_shebang Procedure
47 statements
Source File
module procedure whole_shebang module procedure whole_shebang()
Uses
calc_rtndt
calc_k
calc_cpi
material_content_m
data_partition_interface
Arguments
None
Calls
Contents
None
Call graph
whole_shebang calls rtndt, cpi_hist, k_hist, cpi_t, cf, gather, assert, output_data_t, temp, random_samples
k_hist calls k_hist
gather calls gather