! Generated by make_vegetable_driver. DO NOT EDIT
program main
    implicit none

    call run()
contains
    subroutine run()
        use random_samples_tests, only: &
                random_samples_tests_test_random_samples => test_random_samples
        use vegetables, only: test_item_t, test_that, run_tests

        type(test_item_t) :: tests
        type(test_item_t) :: individual_tests(1)

        individual_tests(1) = random_samples_tests_test_random_samples()
        tests = test_that(individual_tests)

        call run_tests(tests)
    end subroutine
end program
